### PR TITLE
Add example snippets and update documentation

### PR DESCRIPTION
**Pull request by alexgibson**
Taking a shot at adding some structure for forthcoming pull requests

### CODE REVIEW

**Comment by alexgibson** [comment]
@jpetto @pmclanahan r?

**Comment by pmclanahan** [comment]
This looks to me like a wonderful start! Thanks Alex!! I'll let @jpetto have a look as well before we merge, but it's an r+ from me. :rocket:

**Comment by jpetto** [comment]
Two suggestions:
1. Add instructions for Optimizely tests with multiple variations. Better to be specific than force committers to invent a format/structure.
2. Update the provided snippets to include _everything_ possible for easy use as copy/paste templates. Could make the code simple/short to minimize file size, as long as all the placeholders are present. Thinking this will reduce friction, making creating PRs simpler for committers.

**Comment by alexgibson** [comment]
> Add instructions for Optimizely tests with multiple variations. Better to be specific than force committers to invent a format/structure.

Good suggestion :+1: 

> Update the provided snippets to include everything possible for easy use as copy/paste templates. Could make the code simple/short to minimize file size, as long as all the placeholders are present. Thinking this will reduce friction, making creating PRs simpler for committers.

This sounds good to me, I'll update both examples to be generic placeholders that can be copy / pasted as templates. The GTM one may be a little sparse initially, as I really have not much clue about what's needed. Hopefully we can expand on it once someone from AP shares some code.

**Comment by alexgibson** [comment]
@jpetto updated based on your comments. I don't think we'll get everything right first time here, but it's hopefully a start toward some kind of workable process. Let me know what you think?

**Comment by jpetto** [comment]
Love it! r+ from me. :hatching_chick:

**Pull request merged**
